version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: sh -c "go mod tidy && CGO_ENABLED=0 GOOS=linux go build -o main . && /app/main"
    environment:
      - ENV=production
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/angular
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge